/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package adv_bounce_effect */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "physics.go"

#include <stdint.h>

typedef struct {
    // ---- core physics / timing ----
    double gravity;
    double bounciness_vertical;
    double bounciness_horizontal;
    double max_speed;
    double fps;

    // initial velocity
    double initial_vx;
    double initial_vy;

    // ---- air drag (per-second rates) ----
    int    enable_air_drag_x;
    int    enable_air_drag_y;
    double air_drag_x_rate;
    double air_drag_y_rate;
	double air_drag_x_min_speed;
    double air_drag_y_min_speed;

    // ---- spin torque ----
    int    enable_spin_torque;
    double spin_torque_strength;

    // ---- squish ----
    int    squish_enabled;
    double squish_decay_rate; // per second
    double squish_factor;
    double squish_max;

    // ---- random impulse on bounce ----
    int    enable_random_impulse_x;
	int    enable_random_impulse_y;
    double rand_impulse_x_min;
    double rand_impulse_x_max;
    double rand_impulse_y_min;
    double rand_impulse_y_max;
	double rand_impulse_x_max_speed;
	double rand_impulse_y_max_speed;

    // ---- bounce flicker ----
    int    enable_bounce_flicker;
    double flicker_decay_rate; // per second

    // ---- impact squash ----
    int    enable_impact_squash;
    double impact_squash_mult;
    double impact_recovery_rate; // per second

    // ---- squish tilt ----
    int    enable_squish_tilt;
    double tilt_factor;

    // ---- magnetic squish ----
    int    enable_magnetic_squish;
    double magnetic_range;
    double magnetic_strength;

    // ---- jiggle ----
    int    enable_jiggle;
    double jiggle_strength;
    double jiggle_freq;
    double jiggle_decay_rate; // per second

    // ---- stuck / unsticking ----
    double stuck_y_tolerance;
    double stuck_threshold_time;
    double stuck_impulse_min;
    double stuck_impulse_max;

    // ---- rendering radii ----
    double ball_radius;
    double halo_radius;

    // ---- trail ----
    int    enable_trail_effect;
    double trail_new_color_percent; // 0..1

    // ---- color modes ----
    int    enable_rainbow_ball;
    int    enable_heatmap_glow;

    // BALL_COLOR
    uint8_t ball_r;
    uint8_t ball_g;
    uint8_t ball_b;

    // BACKGROUND_COLOR
    uint8_t bg_r;
    uint8_t bg_g;
    uint8_t bg_b;
} EffectConfig;

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void InitEffect(EffectConfig* cfg, int ledCount);
extern void StepEffect(double dt, double now);
extern void GetFrame(double* posOut, unsigned char* colOut);

#ifdef __cplusplus
}
#endif
